=pod

=encoding utf8

=head1 NAME

TVS

=head1 SYNOPSIS

	./tvs daemon

=head1 DESCRIPTION

A simple web based auto-syndicated rss portal.

=head2 CPAN Setup

	cpanm -S Modern::Perl Mojolicious::Lite DBI DBD::mysql XML::Simple XML::RSS::Feed HTML::Entities HTML::Strip

=head2 Add Feeds to MySQL
	
	scripts/dbupdate
	
=head1 BUGS

	http://github.com/ispyhumanfly/tvs/issues

=head1 SEE ALSO

	http://wiki.github.com/ispyhumanfly/tvs/wiki

=head1 LICENSE

This is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut
