#!/usr/bin/env perl

use local::lib 'lib';

use Mojolicious::Lite;

use lib 'library';
use Model;

my $MODEL = Model->new;

get '/' => sub {

    my $self = shift;
    $self->render('home', layout => 'default');

};

#### Pages...

get '/home' => sub {

    my $self = shift;

    $self->{articles} = $MODEL->get_articles(list => 'home');

    $self->render('home', layout => 'default');

} => 'home';

get '/featured' => sub {

    my $self = shift;

    $self->{articles} = $MODEL->get_articles(list => 'featured');

    $self->render('featured', layout => 'default');

} => 'featured';

get '/watch_list' => sub {

    my $self = shift;

    $self->{articles} = $MODEL->get_articles(list => 'watch_list');

    $self->render('watch_list', layout => 'default');

} => 'watch_list';

get '/inbox' => sub {

    my $self = shift;

    $self->{articles} = $MODEL->get_articles(list => 'inbox');

    ### I'm experimenting with a filter feature...

    if ($self->param('filter')) {

        my @results;

        for (@{ $self->{articles} }) {

            my $string = $self->param('filter');

            push @results, $_ if $_->{title} =~ /$string/i;
        }

        $self->{articles} = \@results;
    }

    $self->render('inbox', layout => 'default');

} => 'inbox';

### Functions...

post '/vote' => sub {

    my $self = shift;

    if (($self->param('name')) and ($self->param('tbl_id'))) {

        $MODEL->do_vote(
            name   => $self->param('name'),
            tbl_id => $self->param('tbl_id')
        );
    }

} => 'vote';

post '/model' => sub {

    my $self = shift;

    $MODEL->get_feeds()
      if $self->param('get_feeds');

    $MODEL->do_prune()
      if $self->param('do_prune');

    $MODEL->do_rss()
      if $self->param('do_rss');

    $self->redirect_to('/');

} => 'model';

app->secret('TVS Rocks!');
app->start;
