#!/usr/bin/env perl

use Mojolicious::Lite;

use lib 'library';
use Model;

sub startup {

    # preamble...
    my $self = shift;

    # initiate the Model class...
    $self->{'model'} = new Model;

}

get '/' => sub {

    my $self = shift;
    
} => 'index';

app->start;
