#!/usr/bin/env perl

use Modern::Perl;

use lib 'library';
use Model;

my $MODEL = Model->new;

my @Articles = qw/ inbox watch_list featured /;

for (@Articles) {

    my $article = $MODEL->get_articles(list => $_ );

    say $_;
    say "\t$_->{title}" for @{$article};

}
