#!/usr/bin/env perl

use Modern::Perl;

use Getopt::Long qw/:config no_ignore_case /;
use Pod::Usage;
use Cwd qw/ realpath /;

use lib 'library';
use Model;

my $MODEL = Model->new;

my %obj;

GetOptions(

    'commands|c=s' => \@{$obj{'commands'}},
    'help|?|h'     => \$obj{'help'},
);

pod2usage "\nTVS Command-Line Tools.\n"
  if defined $obj{help}
      or not $ARGV[0];

for (@{$obj{commands}) {

    if ($_ eq 'prune') {
    
        say 'Pruning the database...';
        $MODEL->do_prune();
    }
    elsif ($_ eq 'rss') {
        
        say 'Generating an RSS feed...';
        $MODEL->do_rss();
    }
    elsif ($_ eq 'feeds') {
        
        say 'Checking for new feed content...';
        $MODEL->get_feeds();
    }
}

__END__

=head1 SYNOPSIS

<file/device> <-o file.mp4> [options]

Options:

  -h, -?, --help  This help / usage screen...
  -c, --commands  Output file name...

Example: scripts/tvtools -c prune,rss,update

=cut
